apiVersion: v1
kind: Pod
metadata:
  name: simpleservice
  namespace: kube-public
  labels:
    name: simpleservice
spec:
  containers:
  -
    name: simpleservice-web
    image: mhausenblas/simpleservice:0.5.0
    ports:
    -
      name: web
      containerPort: 9876
      protocol: TCP
