apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"what":"what"},"name":"nginx","namespace":"default"},"spec":{"containers":[{"image":"nginx:1.7.9","name":"nginx","ports":[{"containerPort":80}]}]}}
  creationTimestamp: "2020-01-22T22:21:51Z"
  labels:
    app: web_service
    importance: critical
    customer: internal_use
    what: what
  name: nginx
  namespace: default
  resourceVersion: "295754"
  selfLink: /api/v1/namespaces/default/pods/nginx
  uid: 61ab4116-38e7-4fd1-813e-20eccf0273bb
spec:
  containers:
  - image: nginx:1.7.9
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-9rhqv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-241-node-02
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-9rhqv
    secret:
      defaultMode: 420
      secretName: default-token-9rhqv
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:21:50Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:22:22Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:22:22Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:21:51Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a66f15d8000c4d58b0ae853b33cb95fc2bf0b01eb544eefa73952953dd188dbf
    image: docker.io/library/nginx:1.7.9
    imageID: sha256:35d28df486f6150fa3174367499d1eb01f22f5a410afe4b9581ac0e0e58b3eaf
    lastState:
      terminated:
        containerID: containerd://a81599a0b8c4a10d82b8735b578731fd0245c5d66213ac7db97759972bf4862b
        exitCode: 0
        finishedAt: "2020-01-22T22:22:20Z"
        reason: Completed
        startedAt: "2020-01-22T22:21:52Z"
    name: nginx
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: "2020-01-22T22:22:22Z"
  hostIP: 10.14.249.8
  phase: Running
  podIP: 192.168.67.223
  qosClass: BestEffort
  startTime: "2020-01-22T22:21:50Z"
