apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: sise
  name: sise-deploy
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/sise-deploy
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sise
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sise
    spec:
      containers:
      - env:
        - name: SIMPLE_SERVICE_VERSION
          value: "1.0"
        image: mhausenblas/simpleservice:0.5.0
        imagePullPolicy: IfNotPresent
        name: sise
        ports:
        - containerPort: 9876
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
